/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author 114310771
 */
public class FormCustomerHomepage extends javax.swing.JFrame {
    private Customer customer;
    private Order order;
    private Notification notification;
    private Notification notificationCancel;
    /**
     * Creates new form Orders
     */
    public FormCustomerHomepage() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.start();
        lblTime.setVisible(false);
        lblTimeTime.setVisible(false);
        lblDriver.setVisible(false);
        lblDriverName.setVisible(false);
    }

    Timer timer = new Timer(2000, new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            IOdb database = new IOdb();
            try {
                notification = database.checkForNotification("CUSTOMER", customer.getID());
                if(notification.getNotificationID()!=0) {                    
                        if("TRIP_ACCEPTED".equals(notification.getMessage())) {
                            notificationCancel=notification;
                            JOptionPane.showMessageDialog(null, "Trip accepted!", "InfoBox: " + "Login", JOptionPane.INFORMATION_MESSAGE);
                            customer.handleNotification(notification);
                            order = database.getOrder(notification.getOrderID());
                            txtPickUpPoint.setEnabled(false);
                            txtDestination.setEnabled(false);
                            lblDriver.setVisible(true);
                            lblTime.setVisible(true);
                            chkPickMeUphere.setEnabled(false);
                            lblTimeTime.setVisible(true);
                            lblDriverName.setVisible(true);
                            lblTimeTime.setText(String.valueOf(order.getTravelTime()) + " minutes");
                            lblDriverName.setText(String.valueOf(notification.getDriverID()));
                            btnRequest.setEnabled(false);
                            btnCancelOrder.setEnabled(true);
                        }
                    }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error getting a notification!", "Error" + "Login", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    });    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPickUpPoint = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        txtPickUpPoint = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        btnRequest = new javax.swing.JButton();
        chkPickMeUphere = new javax.swing.JCheckBox();
        lblDriver = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDriverName = new javax.swing.JLabel();
        lblTimeTime = new javax.swing.JLabel();
        btnCancelOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPickUpPoint.setText("Pick Up Point");

        lblDestination.setText("Destination");

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        chkPickMeUphere.setText("Pick Me Up Here");
        chkPickMeUphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPickMeUphereActionPerformed(evt);
            }
        });

        lblDriver.setText("Driver ID:");

        lblTime.setText("Time:");

        lblDriverName.setText("jLabel1");

        lblTimeTime.setText("jLabel1");

        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.setEnabled(false);
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPickUpPoint)
                            .addComponent(lblDestination))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPickMeUphere)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPickUpPoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(txtDestination, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDriver)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTimeTime))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDriverName)))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDriver)
                    .addComponent(jLabel3)
                    .addComponent(lblDriverName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(jLabel4)
                    .addComponent(lblTimeTime))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPickUpPoint)
                    .addComponent(txtPickUpPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestination)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPickMeUphere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnCancelOrder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        JOptionPane.showMessageDialog(null, "Wait for a driver to respond", "Wait" + "Login", JOptionPane.INFORMATION_MESSAGE);
        String pickUpPoint = txtPickUpPoint.getText();
        String destination = txtDestination.getText();
        customer.orderTaxi(pickUpPoint, destination);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void chkPickMeUphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPickMeUphereActionPerformed
        if("Here".equals(txtPickUpPoint.getText())) {
            txtPickUpPoint.setText("");
            txtPickUpPoint.setEnabled(true);
        } else {
            txtPickUpPoint.setText("Here");
            txtPickUpPoint.setEnabled(false);
        }

    }//GEN-LAST:event_chkPickMeUphereActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        customer.cancelTaxi(notificationCancel.getOrderID());
        txtPickUpPoint.setEnabled(true);
        txtDestination.setEnabled(true);
        lblDriver.setVisible(false);
        lblTime.setVisible(false);
        chkPickMeUphere.setEnabled(true);
        lblTimeTime.setVisible(false);
        lblDriverName.setVisible(false);
        lblTimeTime.setText("");
        lblDriverName.setText("");
        btnRequest.setEnabled(true);
        btnCancelOrder.setEnabled(false);
        txtPickUpPoint.setText("");
        txtDestination.setText("");
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCustomerHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCustomerHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCustomerHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCustomerHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCustomerHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnRequest;
    private javax.swing.JCheckBox chkPickMeUphere;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblDriverName;
    private javax.swing.JLabel lblPickUpPoint;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtPickUpPoint;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * @param customer the customer to set
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
}
